# NUMPY

In [3]:
!pip install numpy


In [4]:
import numpy as np

# 1.1 convet list into array 

In [6]:
import numpy as np
a = [1,2,3,4]
b = np.array(a)
print(a)
print(b)
print(a*2)
print(b*2)

[1, 2, 3, 4]
[1 2 3 4]
[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


#   1.2 creating an array

In [10]:
a = np.array([1,2,3])
print(a)
print('----------------')
b = np.array([[1,2],[2,4]])
print(b)
print('----------------')
c = np.zeros((2,3))
print(c)
print('----------------')
d = np.ones((3,3))
print(d)
print('----------------')
e = np.arange(0,10,2)
print(e)
print('----------------')
f = np.linspace(0,1,5)
print(f)

[1 2 3]
----------------
[[1 2]
 [2 4]]
----------------
[[0. 0. 0.]
 [0. 0. 0.]]
----------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
----------------
[0 2 4 6 8]
----------------
[0.   0.25 0.5  0.75 1.  ]


# 1.3 array properties


In [26]:
arr = np.array([[1,2,3] , [4,5,6]])
print(' 1 . shape os array like row and column')
print('----',arr.shape)
print(' 2 . sizew of array like element in array')
print('----',arr.size)
print('3 . dimention of array like matrix or not something like that')
print('----',arr.ndim)
print('4 . date type of the element like number or string ')
print('----',arr.dtype)

 1 . shape os array like row and column
---- (2, 3)
 2 . sizew of array like element in array
---- 6
3 . dimention of array like matrix or not something like that
---- 2
4 . date type of the element like number or string 
---- int64


# 1.4 indexing and slicing

In [28]:
arr = np.array([[1,2,3] , 
                [4,5,6]])
print(arr[0,1])   #2
print(arr[:, 1])   


2
[2 5]


# 1.5 arrray reshaping 

In [22]:
a = np.arange(1,7)  # get no. 1 to 6 , 7 is skip 
b = a.reshape(2,3)  #(row , column)
b

array([[1, 2, 3],
       [4, 5, 6]])

# 1.6 array operation ( *, / , + , - )

In [24]:
a = np.array([10,20,30])
b = np.array([1,2,3])
c = np.array([4,9,16])
print(a+b)
print(a-b)
print(a/b)
print(a*b)
print(np.sqrt(c))   # square root 

[11 22 33]
[ 9 18 27]
[10. 10. 10.]
[10 40 90]
[2. 3. 4.]


# 1.7 statistical funtions 

In [31]:
arr = np.array([10,20,30,40,])
print(np.mean(arr))     #mean
print(np.median(arr))   #median
print(np.std(arr))      #standard deviation
print(np.min(arr))      #minimum value
print(np.max(arr))      # mazimum value

25.0
25.0
11.180339887498949
10
40


# 1.8 mathematical function

In [36]:
a = np.array([0 , np.pi/2 , np.pi])
print('Array : ',a)
print(np.sin(a))                          #sin
print(np.log([1,np.e , np.e**2]))         #e = exponential value           
print(np.exp([1,2,3]))
np.e

Array :  [0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[0. 1. 2.]
[ 2.71828183  7.3890561  20.08553692]


2.718281828459045

# 1.9 random numbers

In [37]:
print(np.random.rand(3))                #give no between 0-1 , 3 no.
print(np.random.randint(1,10))          # give any one no. between 1-10
print(np.random.randint(1,10,(2,3)))    # give matxic of row and column 
                    #  (starting no

[0.44009273 0.41641468 0.40189017]
6
[[9 6 1]
 [7 1 4]]


# 1.10 aggreagate function


In [42]:
a = np.array([[5,1,3] ,[2,3,4]])
print('sum column of matrix ')
print('---',np.sum(a,axis= 0))
print('sum row of matrix ')
print('---',np.sum(a ,axis=1))





sum column of matrix 
--- [7 4 7]
sum row of matrix 
--- [9 9]


# 1.11 copy view

In [49]:
a = np.array([1,2,3])
b = a.view()
c = a.copy()   #duplicate of array , if change in array , don't effect the copy 
a[0] = 88
print(b,'\n',c)

[88  2  3] 
 [1 2 3]


# 1.12 array manipulation

In [51]:
a = np.array([1,2,3])
b = np.array([3,4,5])
print(np.concatenate((a,b)))   # concate the array
print(np.vstack((a,b)))        # vstack = put array up and down
print(np.hstack((a,b)))


[1 2 3 3 4 5]
[[1 2 3]
 [3 4 5]]
[1 2 3 3 4 5]


# 1.13 spliting 


In [53]:
a = np.array([10,20,30,40,50,60])
b = np.split(a , 3)               #split 
print(b)

[array([10, 20]), array([30, 40]), array([50, 60])]


# 1.14 boolean indexing

In [56]:
a = np.array([10,23,35])
print(a[a>20])                #print the no. in 

[23 35]


# 1.15 vectorized computation

In [ ]:
import time 

# 1.16 handling missing or special value

In [60]:
arr = np.array([1,2,np.nan, 4])
print(np.nanmean(arr))
print(arr)

2.3333333333333335
[ 1.  2. nan  4.]


# 1.17 save and load value

In [63]:
a = np.array([1,2,3,4])
np.save('data.npy' ,a)
loaded = np.load('data.npy')

# round 